# Set to false if you don't want to use our TAB list feature
use_tab: true

# Set to false if you don't want to use our bossbar feature
use_bossbar: true
# How many seconds to wait before going to the next message
bossbar_interval: 5
# Color options: BLUE RED PINK GREEN PURPLE WHITE YELLOW
bossbar_color: "BLUE"
# This represents a percentage of how full the bar should be colored in
# Examples: Just a quarter = 25, halfway = 50, 3 quarts = 75
# Keep the range between 0 and 100!
bossbar_fill_precentage: 100

# Used internally for configuration updates.
# ⚠️ Do not change this value.
config_version: 0
