name: LyttleTab
description: Custom tab plugin
version: '${projectVersion}'
main: com.lyttledev.lyttletab.LyttleTab
api-version: '1.21'
authors:
  - LyttleDevelopment
  - ThatsATim
  - Stualyttle

commands:
  lyttletab:
    description: Admin command, mainly reload the config without the rest of the server
    permission: lyttletab.lyttletab